import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import ProductCard from '../components/product-card';

const Home: NextPage = () => {
  return (
    <div className="md:p-16 p-3 h-screen w-screen bg-red-300">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductCard
        name="Classic Utility Jacket"
        price={110}
        imgSrc="/images/jacket.jpeg"
        instock={true}
      ></ProductCard>
    </div>
  );
  2;
};

export default Home;
